<?php


include_once $_SERVER['DOCUMENT_ROOT']."/_config/db.connect.php";
include_once $_SERVER['DOCUMENT_ROOT']."/_config/sys.config.php";
include_once $_SERVER['DOCUMENT_ROOT']."/_config/board.config.php";
include_once $_SERVER['DOCUMENT_ROOT']."/_libs/base_lib.php";
include_once $_SERVER['DOCUMENT_ROOT']."/_libs/admin_libs.php";



if(!$_COOKIE['_CKE_USER_ID']){
	popupMsg("로그인 후 이용해주세요",1);
	exit();
}

/* DB Connection */
$DB = DBConn($_HOST_NAME, $_USER_NAME, $_PASSWORD, $_DB);


$memIdx = $_COOKIE['_CKE_USER_UID'];

$anal = 0;
$cnt = 0;

$sql = "select count(idx) as cnt,anal, regDate from 2020PointChange where uIdx = $memIdx group by idx";
$tmpRs = mysql_query($sql);
$rs = mysql_fetch_array($tmpRs);

$cnt = $rs[cnt];
$anal = $rs[anal];

//echo $cnt."  ".$anal;

?>

<html>
<title>포인트 서비스로 전환하기</title>
<head>
<script>

function cancelService(){
	
	var msg = "신청을 취소하시겠습니까?";	
		
			if(confirm(msg) == true)  
			{
				document.form1.action="202004_pointChangeCancelOk.php";
				document.form1.submit();
			}
			else
			{
				return false;
			}
}

function setService(_value){
	
	var msg = "";
	
		if(_value == '1'){
			
			msg = "평택촌놈 통합방송을 선택하신게 맞습니까?";
			
		}else if(_value == '2'){
			msg = "평택촌놈 현물SMS를 선택하신게 맞습니까?";
			
		}else if(_value == '3'){
			msg = "파생SMS를 선택하신게 맞습니까?";
			
		}else if(_value == '4'){
			msg = "봉추선생 채팅방송을 선택하신게 맞습니까?";			
		}
	
        if(confirm(msg) == true)  
        {
			
            document.getElementById("analSelect").value=_value;
			document.form1.action="202004_pointChangeOk.php";
			document.form1.submit();
        }
        else
        {
            return false;
        }
	
}

</script>
</head>
<body>
<!--
<input id="tblbutton" type="button" value="평택촌놈 통합방송" onclick="setService('1');">
<input id="tblbutton" type="button" value="평택촌놈 현물" onclick="setService('2');">
<input id="tblbutton" type="button" value="평택촌놈 파생" onclick="setService('3');">
<input id="tblbutton" type="button" value="봉추선생 채팅방송" onclick="setService('4');">
-->

<script>
alert("신청 마감되었습니다");
location.href="http://www.502.co.kr";
</script>

<!-- Image Map Generated by http://www.image-map.net/ -->
<?php
if($anal == 0){
	?>
<img src="http://www.502.co.kr/upload_file/WImgPost/2020/04/1586395705038.jpg" usemap="#image-map">

<map name="image-map">
    <area alt="평택촌놈 통합방송" title="평택촌놈 통합방송" onclick="setService('1');" coords="626,631,817,676" shape="rect">
    <area alt="평택촌놈 현물SMS" title="평택촌놈 현물SMS" onclick="setService('2');" coords="627,698,817,737" shape="rect">
    <area alt="평택촌놈 파생SMS" title="평택촌놈 파생SMS" onclick="setService('3');" coords="627,761,817,799" shape="rect">
    <area alt="서비스 신청 취소" title="봉추선생 채팅방송" onclick="setService('4');" coords="625,821,822,866" shape="rect">
</map>
<?php
}else if($anal == 1)
{
	?>
	<img src="http://www.502.co.kr/upload_file/WImgPost/2020/04/1586395711617.jpg" onclick="cancelService();">
	<?php
}else if($anal == 2)
{
	?>
	<img src="http://www.502.co.kr/upload_file/WImgPost/2020/04/1586395719784.jpg" onclick="cancelService();">
	<?php
}else if($anal == 3)
{
	?>
	<img src="http://www.502.co.kr/upload_file/WImgPost/2020/04/1586395729706.jpg" onclick="cancelService();">
	<?php
}else if($anal == 4)
{
	?>
	<img src="http://www.502.co.kr/upload_file/WImgPost/2020/04/1586395737639.jpg" onclick="cancelService();">
	<?php
}
?>

<form name="form1" method="POST" ACTION="">
	<input type="Hidden" name="userId" id="userId" value="<?=$_COOKIE['_CKE_USER_ID']?>">
	<input type="Hidden" name="analSelect" id="analSelect" value="">	
</form>

</body>

</html>
